### ISSUE TITLE
ModBB throws error: No parameter 'write_lossless' has been specified!

### ISSUE THREAD

**Issue by alexjcwitsil** [chetzer-ncpa/ncpaprop-release#34]
I recently installed NCPAProp on a shared HPC (Ubuntu 20.04.5 LTS (GNU/Linux 5.4.0-144-generic x86_64))
The installation, as far as I can tell, went on without a hitch (hooray!) 
However, when trying to run ModBB, I am getting an error. 

Specifically, when trying to run: 

`ModBB --dispersion --dispersion_file test_dispersion.dat --atmosfile NCPA_canonical_profile_zuvwtdp.dat --azimuth 90 --f_min 0.01 --f_step 0.01 --f_max 0.5 --method modess`

I get the error:

terminate called after throwing an instance of 'std::invalid_argument'
  what():  No parameter 'write_lossless' has been specified!

I can run other examples from the manual including examples using `Modess` so am unsure as to why `ModBB` is failing.  

Thanks in advance for the help!

**Comment by chetzer-ncpa** [comment]
Issue was due to the Modess library expecting a --write_lossless option, while the more streamlined ModBB calculation doesn't support turning that option on.  Added a dummy parameter to eliminate the error.  Future refactoring plans will account for this and remove the necessity for the dummy parameter.
